### ISSUE TITLE
Add field for files/directories to ignore when linting

### ISSUE THREAD

**Issue by rictic** [Polymer/polymer-project-config#11]

**Comment by stramel** [comment]
Would you like a hand with this @rictic?

**Comment by stramel** [comment]
@rictic This seems like it has been addressed? 

https://github.com/Polymer/polymer-project-config/blob/2ef2bb237add1e4022a98d10e599b56334730ae6/src/index.ts#L113-L123

**Comment by rictic** [comment]
Looks right. Still need to hook it up in WarningFilter and in the CLI.

**Comment by stramel** [comment]
Appears to already be hooked up to Analyzer's `WarningFilter` as well
