### ISSUE TITLE
Move higher-level configuration parsing & validating out of shared config?

### ISSUE THREAD

**Issue by FredKSchott** [Polymer/polymer-project-config#18]
I'm not sure if we have a good enough reason to make this change yet, or even if we want to make this change, but I wanted to start this issue to track the conversation if things change.

## Background 
Currently PolymerProjectConfig is responsible for the parsing and validation of two, high-level configurations: "build" and "lint". Each of these is read and understood by only a single tool (Polymer CLI). 

The path we're currently on is to continue to add all config parsing responsibilities to PolymerProjectConfig. Just today I added more logic to the "build" property parser to handle presets.

The question is: should the shared PolymerProjectConfig class, responsible for all polymer.json parsing, be responsible for parsing & validating these higher-level config formats that are only used by a single other tool? Or, should that tool be responsible for it?

#### Reasons to keep in PolymerProjectConfig
- One shared place to define, parse, and validate configuration. 
- Configuration can't mean different things to different tools.
- 3rd party tooling can still define "unsupported" configurations which are simply propagated to PolymerProjectConfig (but not parsed or validated in any way).

#### Reasons to move to Polymer CLI
- `config.validate()` currently validates the entire polymer.json. That means that even an unrelated issue can stop a validating program from running (ex: `polymer lint` will fail validation if there's an issue in one of the build configs).
- Not having to parse or validate unrelated configuration = better performance.
- Tools will be able to interpret the user-provided configuration, instead of the parsed configuration (ex: a build preset is applied at parse time, so a tool would never be able to see what was set by the user vs. the preset).

/cc @rictic @usergenic @justinfagnani who have all touched this file in some way.

**Comment by rictic** [comment]
So, the ideal from a user experience would be to generate warnings but only halt if the config is invalid from the perspective of the task at hand. So `polymer build` would complete if the `lint` section was invalid, but it might print a warning and exit with a non-zero exit code.

I think the next best thing would be to do validation in one place, provided that the errors that we throw have enough information and are worded usefully.

**Comment by justinfagnani** [comment]
Our validation should be pretty loose, and I'm under the impression that the generated validator should be by default. So it shouldn't be rejecting on unknown properties, just missing required values and bad types. I think this is lenient enough to always perform.

For UX, we can stop throwing on validation errors, but return or store them with the returned config, and add API for accessing paths of the config that return errors if present for those paths, ie:

```
const config = ProjectConfig.loadOptionsFromFile(path);
if (config.getErrors('lint')) {
  console.error('Errors in lint configuration');
}
```

This might just be too much work for too little gain. I don't think the current situation is too inhibiting in the absence of complaints.

**Comment by FredKSchott** [comment]
Thanks for the feedback guys. Totally agreed with you both that the current situation isn't "terrible", and all issues that the validator currently picks up are quick fixes for the user to make. 

- I like the idea of returning an error report instead of just throwing
- For a least effort solution, If we returned more information on the error object we could do something like the following: 
```js
// in the build command (strawman)
try {
  project.validate();
} catch (err) {
  (err.category === 'structure' || err.category === 'build') && throw err;
}
```
